services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "88:80"
    restart: always
    environment:
      - VITE_API_BASE_URL=http://frontend:80/api
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
# services:
#   frontend:
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     ports:
#       - "88:80" # Host port 88 maps to container port 80
#     restart: always
#     environment:
#       - VITE_API_BASE_URL=http://frontend:80/api # Route API requests through Nginx
#     networks:
#       - app-network # Network for communication with backend
# networks:
#   app-network:
#     driver: bridge # Bridge network for service communication
