# version: '3'

# services:
#   frontend:
#     image: sag_frontend_gg
#     ports:
#       - "3000:80"  # or whatever port your app uses
#     restart: always


version: '3.9'

services:
  frontend:
    build:
      context: ./frontend  # Make sure this is the path to your frontend folder
    ports:
      - "80:80"  # Exposes port 80 from the container to port 80 on your host
    environment:
      - VITE_API_BASE_URL=http://backend:9002  # Make sure to adjust this based on your backend service
   