

services:
  frontend:
    build:
      context: .  # Path to the frontend folder containing Dockerfile
      dockerfile: Dockerfile  # Name of the Dockerfile
    ports:
      - "88:80"  # Host port 88 maps to container port 80
    restart: always
    environment:
      - VITE_API_BASE_URL=http://backend:9002  # Adjust to your backend's URL
    networks:
      - app-network  # Network for potential future backend integration

networks:
  app-network:
    driver: bridge  # Bridge network for service communication