

services:
  frontend:
    build:
      context: ./ # Make sure this is the path to your frontend folder
      dockerfile: Dockerfile  # Ensure this is the correct Dockerfile for your frontend
    ports:
      - "88:80"  #  port mapping for first is host and second is container port
    restart: always
    environment:
      - VITE_API_BASE_URL=http://backend:9002  # Make sure to adjust this based on your backend service

   